import { StyleSheet } from "react-native";

export const COLORS = {
  surface: "#f8f9fa",
  surfaceLow: "#f3f4f5",
  card: "#ffffff",
  primary: "#000613",
  primaryContainer: "#001f3f",
  onPrimary: "#ffffff",
  secondary: "#0058bc",
  textMuted: "#43474e",
  textSoft: "#74777f",
  glowTop: "#d4e3ff",
  glowBottom: "#d8e2ff",
  primaryMuted: "rgba(0, 31, 63, 0.38)",
  shadow: "rgba(0, 31, 63, 0.08)",
  divider: "#e1e3e4",
  error: "#ba1a1a",
};

export const styles = StyleSheet.create({
  keyboardView: {
    flex: 1,
    backgroundColor: COLORS.surface,
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -80,
    right: -120,
    width: 280,
    height: 280,
    borderRadius: 999,
    backgroundColor: COLORS.glowTop,
    opacity: 0.55,
    shadowColor: COLORS.glowTop,
    shadowOpacity: 0.4,
    shadowRadius: 80,
    shadowOffset: { width: 0, height: 0 },
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: -120,
    left: -110,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: COLORS.glowBottom,
    opacity: 0.32,
    shadowColor: COLORS.glowBottom,
    shadowOpacity: 0.45,
    shadowRadius: 80,
    shadowOffset: { width: 0, height: 0 },
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingTop: 48,
    paddingBottom: 40,
  },
  brandBlock: {
    alignItems: "center",
    marginBottom: 36,
  },
  logoBadge: {
    width: 68,
    height: 68,
    borderRadius: 22,
    backgroundColor: COLORS.primaryContainer,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
    shadowColor: COLORS.primaryContainer,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  brandTitle: {
    color: COLORS.primaryContainer,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  brandSubtitle: {
    marginTop: 6,
    color: COLORS.textMuted,
    fontSize: 14,
    fontWeight: "500",
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 24,
    shadowColor: COLORS.shadow,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroCopy: {
    alignItems: "center",
    marginBottom: 28,
  },
  title: {
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 12,
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: 15,
    lineHeight: 28,
    fontWeight: "400",
    textAlign: "center",
    maxWidth: 260,
  },
  actionsGroup: {
    gap: 14,
  },
  socialButton: {
    minHeight: 56,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 16,
  },
  appleButton: {
    backgroundColor: COLORS.primary,
  },
  googleButton: {
    backgroundColor: COLORS.surfaceLow,
  },
  socialButtonText: {
    fontSize: 16,
    fontWeight: "700",
  },
  appleButtonText: {
    color: COLORS.onPrimary,
  },
  googleButtonText: {
    color: COLORS.primaryContainer,
  },
  buttonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 28,
    marginBottom: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.divider,
  },
  dividerText: {
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: "500",
  },
  registerButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  registerButtonPressed: {
    opacity: 0.72,
  },
  registerButtonText: {
    color: COLORS.secondary,
    fontSize: 17,
    fontWeight: "700",
  },
  signInLinkButton: {
    marginTop: 4,
    marginBottom: 8,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  signInLinkText: {
    color: COLORS.textMuted,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  credentialsPanel: {
    marginTop: 12,
    marginBottom: 12,
    padding: 18,
    borderRadius: 20,
    backgroundColor: COLORS.surfaceLow,
    gap: 14,
  },
  credentialsTitle: {
    color: COLORS.primaryContainer,
    fontSize: 16,
    fontWeight: "800",
  },
  fieldGroup: {
    gap: 8,
  },
  fieldLabel: {
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  errorText: {
    color: COLORS.error,
    fontSize: 13,
    fontWeight: "500",
  },
  loginButton: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primaryContainer,
    marginTop: 4,
  },
  loginButtonText: {
    color: COLORS.onPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  legalText: {
    marginTop: 22,
    color: COLORS.textSoft,
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 1.2,
    lineHeight: 18,
    textAlign: "center",
  },
  legalLink: {
    color: COLORS.secondary,
  },
  trustSection: {
    alignItems: "center",
    marginTop: 34,
  },
  trustIconRow: {
    flexDirection: "row",
    gap: 28,
    marginBottom: 24,
  },
  footerText: {
    color: COLORS.textSoft,
    fontSize: 14,
    fontWeight: "500",
  },
});
